### ISSUE TITLE
Sorry, this linker is not supported.

### ISSUE THREAD

**Issue by Divine-Ts** [m-bers/Arch-Linux-Arm-M1#3]
Hi, bro , do you know this question?

linux % make menuconfig    
ld: unknown option: --version
ld: unknown linker
scripts/Kconfig.include:56: Sorry, this linker is not supported.
make[2]: *** [menuconfig] Error 1
make[1]: *** [menuconfig] Error 2
make: *** [__sub-make] Error 2

when I build my menuconfig in my Mac 
thx

**Comment by m-bers** [comment]
No, I have no idea, sorry. Is this related to this project?

**Comment by m-bers** [comment]
@Divine-Ts I am going to close this, but let me know if I need to reopen. 
I don't believe there's any reference to`make menuconfig` documented in my readme or anywhere in my scripts.
If you were able to boot Arch Linux ARM on your Apple Silicon Mac and you are trying to do something you are used to doing in Arch Linux, it might not be supported on the ARM version. I would try searching the Arch Linux ARM forums for your issue here: https://archlinuxarm.org/forum/

If the issue does relate to this project specifically, please let me know and I will reopen the case.
